title: Growth Mindset
author: Nathan Williams
email: njwilliams@csbsju.edu
description: > # this means to ignore newlines until "baseurl:"
Focused in finding solutions, fascinated by economics

theme: minima
# social links
twitter_username: NathanEcon # DO NOT include the @ character, or else the build will fail!
github_username:  nathanwilliams1996 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
